### ISSUE TITLE
fail to reproduce infer as the demo

### ISSUE THREAD

**Issue by daiw10** [ldzhangyx/instruct-MusicGen#10]
hi，I use the given finetuned.ckpt and music-large， t5-base model to reproduce the demo in 
https://foul-ice-5ea.notion.site/Instruct-MusicGen-Demo-Page-a1e7d8d474f74df18bda9539d96687ab
with the description "Music piece. Instruct: Add Bass/Piano/Guitar"
only the drums works well. piano and guitar much worse than the demo page. 
like 4th piano and 5th guitar
<img width="1353" alt="image" src="https://github.com/user-attachments/assets/a605b4d8-49e7-43e4-a5d7-7799d4475916">
my result is very noisy. is there any other tips to use src/inference.py to reproduce the demo effect? many thanks!

**Comment by ldzhangyx** [comment]
Thanks for your question. Due to the guitar quality of Slakh, I have to say that the generation of guitar tracks are not as good as other tracks. My suggestion is to generate some tracks and pick the best one.

**Comment by daiw10** [comment]
thanks for reply ! [demo.zip](https://github.com/user-attachments/files/17771082/demo.zip)
but my results sounds much worse than the demo. I wonder whether I miss sth. I just change some code in the inference.py 
```
if __name__ == "__main__":
    model_ckpt_path = "/data/instruct_music/instruct-MusicGen/model_ckpt/finetuned.ckpt"

    drums_instruction = "Music piece. Instruct: Add Drums"
    guitar_instruction = "Music piece. Instruct: Add Guitar"
    bass_instruction = "Music piece. Instruct: Add Bass"
    piano_instruction = "Music piece. Instruct: Add Piano"

    output_audio_path = "/data/instruct_music/instruct-MusicGen/output/"
    value_name = ['drums', 'guitar', 'bass', 'piano']
    for j in range(1,6):
        input_audio_path = "/data/instruct_music/instruct-MusicGen/input_files/paper_demo{}.wav".format(str(j))
        for index, value in enumerate([drums_instruction, guitar_instruction, bass_instruction,  piano_instruction]):
            generate_edited_audio(model_ckpt_path, input_audio_path, value, output_audio_path + str(j)+ "_" + str(value_name[index]) +  '.wav')
```

**Comment by ldzhangyx** [comment]
I looks that your settings are correct. If you are willing to developing new models then I encourage to re-training this model with a better dataset; if you just need to make better audios, then I suggest generate >10 audios and pick one manually or using CLAP similarity (pick the one which has the highest score).

**Comment by daiw10** [comment]
okay! I try to use the CLAP similarity to choose a better result. btw, do u have some suggests for the training dataset  for better piano and guitars result?
