### ISSUE TITLE
Details on trained model

### ISSUE THREAD

**Issue by Saltb0xApps** [ldzhangyx/instruct-MusicGen#2]
1. Does this finetune one of the existing musicgen small/medium/large models, or creates a new model from scratch? 
2. Can this support stereo outputs using musicgen's codebook delay technique, or the model would be restricted to mono outputs only?
3. Can multi GPUs training be supported?
4. Is there a timeline for releasing the inference script?

Apologies for the long list of questions! Really excited by the work you've done here and think this can be scaled up to produce some magical outputs!

**Comment by ldzhangyx** [comment]
1. It is a finetuning model. You need to finetune it on MusicGen medium/large.
2. Theoretically it is supports finetuning the stereo model, but I did not do the experiments.
3. I think it supports multi-GPU training, you can find the hydra config and change it.
4. No clear timeline, but you can find the generate() method in the model python file, which can be easily to used for inference.
