### ISSUE TITLE
Availability of pretrained(fine-tuned) models from paper

### ISSUE THREAD

**Issue by EladDvash** [ldzhangyx/instruct-MusicGen#7]
Hello, I wanted to ask if there are any plans to release the models from the paper for experimenting and inference
Even if the inference code isn't ready yet I'd appreciate if we could get the models themselves

Thanks,
Elad

**Comment by ldzhangyx** [comment]
Hi Elad,

Since we uses Slakh dataset for training, while Slakh dataset contains copyright music. It is my internship project at Sony and I must follow Sony's policy that choosing not to release the ckpt to avoid legal problems. Sorry for that...
